name: Feature
description: "Open a Feature Request"
title: '[FEATURE] '
body:
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "Please describe the desired feature?"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Thank you for taking the time to open a Feature Request. Please be patient as we have many open tickets."
